Document: funkeysynth
Title: Debian funkeysynth Manual
Author: <insert document author here>
Abstract: This manual describes what funkeysynth is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/funkeysynth/funkeysynth.sgml.gz

Format: postscript
Files: /usr/share/doc/funkeysynth/funkeysynth.ps.gz

Format: text
Files: /usr/share/doc/funkeysynth/funkeysynth.text.gz

Format: HTML
Index: /usr/share/doc/funkeysynth/html/index.html
Files: /usr/share/doc/funkeysynth/html/*.html
